# Copyright Contributors to the Open Cluster Management project

patchesStrategicMerge:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../deploy
- servicemonitor.yaml
images:
- name: clusterlifecycle-state-metrics
  newName: quay.io/itdove/clusterlifecycle-state-metrics
  newTag: compute
